base_url = "https://spetz.github.io"
title = "Piotr Gankiewicz (spetz)"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
author = "Piotr Gankiewicz"
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
# mathjax = true
# mathjax_dollar_inline_enable = true

menu = [
]

socials = [
    { name = "github", url = "https://github.com/spetz", icon = "github" },
    { name = "twitter", url = "https://twitter.com/spetzu", icon = "twitter" },
    { name = "linkedin", url = "https://www.linkedin.com/in/piotrgankiewicz/", icon = "linkedin" },
]

custom_css = []

[extra.analytics]
enabled = false
